version: "3.8"

networks:
  yandex:
    driver: bridge

services:

  yndx_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: files_info
    networks: 
      - yandex
    ports:
      - 80:5000
    command: python main.py

  db:
    restart: always
    container_name: postgres
    image: postgres:latest
    networks: 
      - yandex
    ports:
      - 5433:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file: .env